### ISSUE TITLE
Publish on NPM

### ISSUE THREAD

**Issue by AndersonFriaca** [roxeteer/jquery-afterresize#1]
Please, you can publish this package on NPM?

**Comment by roxeteer** [comment]
This plugin is not maintained anymore. There must be other similar plugins already available on npm.

I found at least this: https://www.npmjs.com/package/jquery.resizeend (I have not tried it, and I don't know if it fulfills your needs, though.)

**Comment by AndersonFriaca** [comment]
Thanks
